package frrconfig

// daemonsTemplate is the template for the FRR daemons file.
var daemonsTemplate = `
	# This file tells the frr package which daemons to start.
    #
    # Sample configurations for these daemons can be found in
    # /usr/share/doc/frr/examples/.
    #
    # ATTENTION:
    #
    # When activating a daemon for the first time, a config file, even if it is
    # empty, has to be present *and* be owned by the user and group "frr", else
    # the daemon will not be started by /etc/init.d/frr. The permissions should
    # be u=rw,g=r,o=.
    # When using "vtysh" such a config file is also needed. It should be owned by
    # group "frrvty" and set to ug=rw,o= though. Check /etc/pam.d/frr, too.
    #
    # The watchfrr, zebra and staticd daemons are always started.
    #
    bgpd={{ .Bgpd }}
    ospfd=no
    ospf6d=no
    ripd=no
    ripngd=no
    isisd=no
    pimd=no
    ldpd=no
    nhrpd=no
    eigrpd=no
    babeld=no
    sharpd=no
    pbrd=no
    bfdd={{ .Bfdd }}
    fabricd=no
    vrrpd=no
    pathd=no
    #
    # If this option is set the /etc/init.d/frr script automatically loads
    # the config via "vtysh -b" when the servers are started.
    # Check /etc/pam.d/frr if you intend to use "vtysh"!
    #
    vtysh_enable=yes
    zebra_options="  -A 127.0.0.1 -s 90000000"
    bgpd_options="   -A 127.0.0.1 -p {{ .BGPPort }}"
    ospfd_options="  -A 127.0.0.1"
    ospf6d_options=" -A ::1"
    ripd_options="   -A 127.0.0.1"
    ripngd_options=" -A ::1"
    isisd_options="  -A 127.0.0.1"
    pimd_options="   -A 127.0.0.1"
    ldpd_options="   -A 127.0.0.1"
    nhrpd_options="  -A 127.0.0.1"
    eigrpd_options=" -A 127.0.0.1"
    babeld_options=" -A 127.0.0.1"
    sharpd_options=" -A 127.0.0.1"
    pbrd_options="   -A 127.0.0.1"
    staticd_options="-A 127.0.0.1"
    bfdd_options="   -A 127.0.0.1"
    fabricd_options="-A 127.0.0.1"
    vrrpd_options="  -A 127.0.0.1"
    pathd_options="  -A 127.0.0.1"
    # configuration profile
    #
    #frr_profile="traditional"
    #frr_profile="datacenter"
    #
    # This is the maximum number of FD's that will be available.
    # Upon startup this is read by the control files and ulimit
    # is called.  Uncomment and use a reasonable value for your
    # setup if you are expecting a large number of peers in
    # say BGP.
    #MAX_FDS=1024
    # The list of daemons to watch is automatically generated by the init script.
    #watchfrr_options=""
    # To make watchfrr create/join the specified netns, use the following option:
    #watchfrr_options="--netns"
    # This only has an effect in /etc/frr/<somename>/daemons, and you need to
    # start FRR with "/usr/lib/frr/frrinit.sh start <somename>".
    # for debugging purposes, you can specify a "wrap" command to start instead
    # of starting the daemon directly, e.g. to use valgrind on ospfd:
    #   ospfd_wrap="/usr/bin/valgrind"
    # or you can use "all_wrap" for all daemons, e.g. to use perf record:
    #   all_wrap="/usr/bin/perf record --call-graph -"
    # the normal daemon command is added to this at the end.
`

// frrTemplate is the template for the main FRR config (frr.conf) with BGP configuration.
var frrTemplate = `!
frr defaults traditional
hostname external-frr
log file /tmp/frr.log
log timestamp precision 3
!
debug zebra events
debug zebra kernel
debug zebra rib
debug zebra nht
debug zebra nexthop
debug bgp keepalives
debug bgp neighbor-events
debug bgp nht
debug bgp updates in
debug bgp updates out
debug bgp zebra
debug bgp bfd
debug bfd peer
debug bfd zebra
debug bfd network
debug bfd distributed
!
bfd
!
{{- if .StaticRoutes }}
{{- range .StaticRoutes }}
{{- if eq .AddressFamily "ipv6" }}
ipv6 route {{ .Destination }} {{ .Nexthop }}
{{- else }}
ip route {{ .Destination }} {{ .Nexthop }}
{{- end }}
{{- end }}
!
{{- end }}
{{- if .Unnumbered }}
interface {{ .Unnumbered.InterfaceName }}
 ipv6 nd ra-interval 10
 no ipv6 nd suppress-ra
 exit
!
{{- end }}
router bgp {{ .LocalAS }}
 bgp router-id {{ .RouterID }}
 no bgp ebgp-requires-policy
 no bgp default ipv4-unicast
 no bgp network import-check
{{- if .Unnumbered }}
  neighbor unnumbered peer-group
  neighbor {{ .Unnumbered.InterfaceName }} interface peer-group unnumbered
{{- if .Unnumbered.EnableBFD }}
  neighbor unnumbered bfd
{{- end }}
{{- if .Unnumbered.EnableMultiHop }}
  neighbor unnumbered ebgp-multihop 2
{{- end }}
  neighbor unnumbered remote-as {{ .Unnumbered.RemoteAS }}
  neighbor unnumbered password {{ .Unnumbered.BGPPassword }}
  neighbor unnumbered timers {{ .Unnumbered.TimersKeepalive }} {{ .Unnumbered.TimersHold }}
{{- else }}
{{- range .Neighbors }}
  neighbor {{ .Address }} remote-as {{ .RemoteAS }}
  neighbor {{ .Address }} password {{ .BGPPassword }}
{{- if .EnableBFD }}
  neighbor {{ .Address }} bfd
{{- end }}
{{- if .EnableMultiHop }}
  neighbor {{ .Address }} ebgp-multihop 2
{{- end }}
{{- end }}
{{- end }}
!
address-family ipv4 unicast
{{- if .Unnumbered }}
  neighbor unnumbered activate
{{- else }}
{{- range .Neighbors }}
{{- if .ActivateIPv4 }}
  neighbor {{ .Address }} activate
{{- end }}
{{- end }}
{{- end }}
{{- range .IPv4Networks }}
  network {{ . }}
{{- end }}
exit-address-family
!
address-family ipv6 unicast
{{- if .Unnumbered }}
  neighbor unnumbered activate
{{- else }}
{{- range .Neighbors }}
{{- if .ActivateIPv6 }}
  neighbor {{ .Address }} activate
{{- end }}
{{- end }}
{{- end }}
{{- range .IPv6Networks }}
  network {{ . }}
{{- end }}
exit-address-family
{{- if .Unnumbered }}
!
route-map RMAP permit 10
set ipv6 next-hop prefer-global
!
ipv6 nht resolve-via-default
{{- end }}
!
line vty
!
end
`
