package tests

import (
	"context"
	"fmt"
	"strconv"
	"strings"

	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
	"github.com/rh-ecosystem-edge/eco-goinfra/pkg/nodes"
	performancev2 "github.com/rh-ecosystem-edge/eco-goinfra/pkg/schemes/performanceprofile/performanceprofilev2"
	"github.com/rh-ecosystem-edge/eco-gotests/tests/cnf/core/performance/systemreserved/internal/tsparams"
	. "github.com/rh-ecosystem-edge/eco-gotests/tests/cnf/core/performance/systemreserved"
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/api/resource"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/labels"
)

var _ = Describe("SystemReserved", Ordered, Label(tsparams.LabelSystemReservedValidation), func() {

	var (
		controlPlaneNodes []*nodes.Builder
		workerNodes       []*nodes.Builder
		performanceProfile *performancev2.PerformanceProfile
	)

	BeforeAll(func() {
		By("Getting control plane nodes")
		var err error
		controlPlaneNodes, err = nodes.List(APIClient,
			metav1.ListOptions{LabelSelector: labels.Set{"node-role.kubernetes.io/master": ""}.String()})
		Expect(err).ToNot(HaveOccurred(), "Failed to list control plane nodes")
		Expect(controlPlaneNodes).ToNot(BeEmpty(), "No control plane nodes found")

		By("Getting worker nodes")
		workerNodes, err = nodes.List(APIClient,
			metav1.ListOptions{LabelSelector: labels.Set{"node-role.kubernetes.io/worker": ""}.String()})
		Expect(err).ToNot(HaveOccurred(), "Failed to list worker nodes")

		By("Finding PerformanceProfile")
		// Try to find PerformanceProfile - if name is specified, use it; otherwise find any
		profileName := tsparams.PerformanceProfileName
		if profileName == "" {
			// List all PerformanceProfiles and use the first one
			profileList := &performancev2.PerformanceProfileList{}
			err = APIClient.List(context.TODO(), profileList)
			Expect(err).ToNot(HaveOccurred(), "Failed to list PerformanceProfiles")

			if len(profileList.Items) > 0 {
				performanceProfile = &profileList.Items[0]
				GinkgoWriter.Printf("Found PerformanceProfile: %s\n", performanceProfile.Name)
			} else {
				Skip("No PerformanceProfile found in cluster - skipping systemReserved validation tests")
			}
		} else {
			// Get specific PerformanceProfile by name
			performanceProfile = &performancev2.PerformanceProfile{}
			err = APIClient.Get(context.TODO(),
				metav1.ObjectMeta{Name: profileName}.GetObjectMeta(),
				performanceProfile)
			if err != nil {
				Skip(fmt.Sprintf("PerformanceProfile %s not found - skipping tests", profileName))
			}
		}
	})

	Context("PerformanceProfile systemReserved configuration", func() {
		It("Should contain expected systemReserved values", func() {
			By("Verifying PerformanceProfile exists and has systemReserved configuration")
			Expect(performanceProfile).ToNot(BeNil(), "PerformanceProfile is nil")
			Expect(performanceProfile.Spec).ToNot(BeNil(), "PerformanceProfile spec is nil")

			GinkgoWriter.Printf("PerformanceProfile Name: %s\n", performanceProfile.Name)
			GinkgoWriter.Printf("PerformanceProfile NodeSelector: %v\n", performanceProfile.Spec.NodeSelector)

			// systemReserved configuration can be in different locations depending on the version
			// Try multiple locations to find the configuration

			By("Checking for systemReserved in additionalKernelArgs")
			// Sometimes systemReserved is set via kernel args
			foundSystemReservedConfig := false

			if performanceProfile.Spec.AdditionalKernelRuntimeConfig != nil {
				if len(performanceProfile.Spec.AdditionalKernelRuntimeConfig) > 0 {
					GinkgoWriter.Printf("Found additionalKernelRuntimeConfig: %v\n", performanceProfile.Spec.AdditionalKernelRuntimeConfig)
					foundSystemReservedConfig = true
				}
			}

			// Check WorkloadHints as systemReserved might affect them
			if performanceProfile.Spec.WorkloadHints != nil {
				GinkgoWriter.Printf("WorkloadHints configured: realTime=%v, highPowerConsumption=%v\n",
					performanceProfile.Spec.WorkloadHints.RealTime,
					performanceProfile.Spec.WorkloadHints.HighPowerConsumption)
			}

			// Note: In PerformanceProfile v2, systemReserved is typically applied via MachineConfig
			// generated by the Performance Addon Operator, not directly in the PerformanceProfile spec.
			// The actual validation happens in Test Case 4.2 (kubelet config on nodes).

			// At minimum, verify the PerformanceProfile has CPU configuration which affects systemReserved
			Expect(performanceProfile.Spec.CPU).ToNot(BeNil(), "PerformanceProfile CPU configuration is nil")
			Expect(performanceProfile.Spec.CPU.Reserved).ToNot(BeEmpty(), "PerformanceProfile CPU reserved is empty")
			Expect(performanceProfile.Spec.CPU.Isolated).ToNot(BeEmpty(), "PerformanceProfile CPU isolated is empty")

			GinkgoWriter.Printf("✓ PerformanceProfile has CPU partitioning: reserved=%s, isolated=%s\n",
				performanceProfile.Spec.CPU.Reserved, performanceProfile.Spec.CPU.Isolated)

			// Log that systemReserved will be validated via kubelet config in Test Case 4.2
			GinkgoWriter.Printf("Note: systemReserved memory/CPU values will be validated via kubelet config in Test Case 4.2\n")
		})
	})

	Context("Kubelet systemReserved configuration", func() {
		testNodeSystemReserved := func(nodeList []*nodes.Builder, expectedCPU, expectedMemory string, nodeType string) {
			if len(nodeList) == 0 {
				Skip(fmt.Sprintf("No %s nodes found - skipping kubelet config validation", nodeType))
			}

			for _, node := range nodeList {
				nodeObj := node.Object
				nodeName := nodeObj.Name

				It(fmt.Sprintf("Should have correct systemReserved in /etc/node-sizing.env on %s node %s", nodeType, nodeName), func() {
					By(fmt.Sprintf("Executing debug pod on node %s", nodeName))

					// Read /etc/node-sizing.env from the node
					// Using oc debug node/<node> or direct file read via pod
					cmd := []string{"cat", tsparams.NodeSizingEnvPath}

					// Create debug pod and execute command
					output, err := executeDebugPodCommand(nodeName, cmd)
					Expect(err).ToNot(HaveOccurred(), fmt.Sprintf("Failed to read %s from node %s", tsparams.NodeSizingEnvPath, nodeName))
					Expect(output).ToNot(BeEmpty(), fmt.Sprintf("%s is empty on node %s", tsparams.NodeSizingEnvPath, nodeName))

					By("Parsing node-sizing.env file")
					envVars := parseEnvFile(output)

					By("Verifying SYSTEM_RESERVED_CPU")
					actualCPU, found := envVars["SYSTEM_RESERVED_CPU"]
					Expect(found).To(BeTrue(), fmt.Sprintf("SYSTEM_RESERVED_CPU not found in %s on node %s", tsparams.NodeSizingEnvPath, nodeName))

					// Normalize CPU values for comparison (handle "40" vs "40000m")
					Expect(normalizeCPUValue(actualCPU)).To(Equal(normalizeCPUValue(expectedCPU)),
						fmt.Sprintf("CPU systemReserved mismatch on %s node %s: expected %s, got %s", nodeType, nodeName, expectedCPU, actualCPU))

					By("Verifying SYSTEM_RESERVED_MEMORY")
					actualMemory, found := envVars["SYSTEM_RESERVED_MEMORY"]
					Expect(found).To(BeTrue(), fmt.Sprintf("SYSTEM_RESERVED_MEMORY not found in %s on node %s", tsparams.NodeSizingEnvPath, nodeName))
					Expect(actualMemory).To(Equal(expectedMemory),
						fmt.Sprintf("Memory systemReserved mismatch on %s node %s: expected %s, got %s", nodeType, nodeName, expectedMemory, actualMemory))

					GinkgoWriter.Printf("✓ Node %s has correct systemReserved: CPU=%s, Memory=%s\n", nodeName, actualCPU, actualMemory)
				})
			}
		}

		When("Testing control plane nodes", func() {
			testNodeSystemReserved(controlPlaneNodes, tsparams.ControlPlaneCPUReserved, tsparams.ControlPlaneMemoryReserved, "control-plane")
		})

		When("Testing worker nodes", func() {
			testNodeSystemReserved(workerNodes, tsparams.WorkerCPUReserved, tsparams.WorkerMemoryReserved, "worker")
		})
	})

	Context("Node allocatable capacity validation", func() {
		testNodeAllocatable := func(nodeList []*nodes.Builder, nodeType string) {
			if len(nodeList) == 0 {
				Skip(fmt.Sprintf("No %s nodes found - skipping allocatable validation", nodeType))
			}

			for _, node := range nodeList {
				nodeObj := node.Object
				nodeName := nodeObj.Name

				It(fmt.Sprintf("Should have correct allocatable capacity on %s node %s", nodeType, nodeName), func() {
					By("Getting node capacity and allocatable from status")
					capacity := nodeObj.Status.Capacity
					allocatable := nodeObj.Status.Allocatable

					Expect(capacity).ToNot(BeNil(), fmt.Sprintf("Node %s capacity is nil", nodeName))
					Expect(allocatable).ToNot(BeNil(), fmt.Sprintf("Node %s allocatable is nil", nodeName))

					By("Verifying CPU allocatable is reduced by systemReserved")
					capacityCPU := capacity[corev1.ResourceCPU]
					allocatableCPU := allocatable[corev1.ResourceCPU]

					GinkgoWriter.Printf("Node %s - CPU Capacity: %s, Allocatable: %s\n",
						nodeName, capacityCPU.String(), allocatableCPU.String())

					// Allocatable should be less than capacity
					Expect(allocatableCPU.Cmp(capacityCPU)).To(Equal(-1),
						fmt.Sprintf("Node %s allocatable CPU (%s) should be less than capacity (%s)",
							nodeName, allocatableCPU.String(), capacityCPU.String()))

					By("Verifying Memory allocatable is reduced by systemReserved")
					capacityMemory := capacity[corev1.ResourceMemory]
					allocatableMemory := allocatable[corev1.ResourceMemory]

					GinkgoWriter.Printf("Node %s - Memory Capacity: %s, Allocatable: %s\n",
						nodeName, capacityMemory.String(), allocatableMemory.String())

					// Allocatable should be less than capacity
					Expect(allocatableMemory.Cmp(capacityMemory)).To(Equal(-1),
						fmt.Sprintf("Node %s allocatable memory (%s) should be less than capacity (%s)",
							nodeName, allocatableMemory.String(), capacityMemory.String()))

					// Calculate expected allocatable (approximate - doesn't account for eviction thresholds)
					// This is a sanity check that systemReserved is roughly in effect
					expectedAllocatableCPU := capacityCPU.DeepCopy()
					expectedAllocatableMemory := capacityMemory.DeepCopy()

					// For control plane vs worker, use different systemReserved values
					// Check node role using labels, not string matching on name
					var cpuReserved, memoryReserved string
					_, isControlPlane := nodeObj.Labels["node-role.kubernetes.io/master"]
					if !isControlPlane {
						_, isControlPlane = nodeObj.Labels["node-role.kubernetes.io/control-plane"]
					}

					if isControlPlane {
						cpuReserved = tsparams.ControlPlaneCPUReserved
						memoryReserved = tsparams.ControlPlaneMemoryReserved
					} else {
						cpuReserved = tsparams.WorkerCPUReserved
						memoryReserved = tsparams.WorkerMemoryReserved
					}

					// Parse systemReserved values
					systemReservedCPU, err := resource.ParseQuantity(cpuReserved)
					Expect(err).ToNot(HaveOccurred(), fmt.Sprintf("Failed to parse CPU reserved %s", cpuReserved))

					systemReservedMemory, err := resource.ParseQuantity(memoryReserved)
					Expect(err).ToNot(HaveOccurred(), fmt.Sprintf("Failed to parse memory reserved %s", memoryReserved))

					expectedAllocatableCPU.Sub(systemReservedCPU)
					expectedAllocatableMemory.Sub(systemReservedMemory)

					GinkgoWriter.Printf("Node %s - Expected allocatable (without eviction): CPU~%s, Memory~%s\n",
						nodeName, expectedAllocatableCPU.String(), expectedAllocatableMemory.String())

					// Actual allocatable should be approximately expected (allowing for eviction thresholds)
					// We check that it's less than expected (due to eviction) but more than 90% of expected
					minExpectedCPU := expectedAllocatableCPU.DeepCopy()
					minExpectedCPU.Set(int64(float64(minExpectedCPU.MilliValue()) * 0.9))

					Expect(allocatableCPU.Cmp(minExpectedCPU)).To(BeNumerically(">=", 0),
						fmt.Sprintf("Node %s allocatable CPU (%s) is significantly less than expected (%s)",
							nodeName, allocatableCPU.String(), expectedAllocatableCPU.String()))
				})
			}
		}

		When("Validating control plane node allocatable", func() {
			testNodeAllocatable(controlPlaneNodes, "control-plane")
		})

		When("Validating worker node allocatable", func() {
			testNodeAllocatable(workerNodes, "worker")
		})
	})

	Context("systemReserved enforcement validation", func() {
		testNodeEnforcement := func(nodeList []*nodes.Builder, nodeType string) {
			if len(nodeList) == 0 {
				Skip(fmt.Sprintf("No %s nodes found - skipping enforcement validation", nodeType))
			}

			for _, node := range nodeList {
				nodeObj := node.Object
				nodeName := nodeObj.Name

				It(fmt.Sprintf("Should have systemReserved enforcement enabled on %s node %s", nodeType, nodeName), func() {
					By(fmt.Sprintf("Checking kubelet config enforcement on node %s", nodeName))

					// Read kubelet configuration to verify enforcement settings
					cmd := []string{"cat", "/host/var/lib/kubelet/config.json"}
					output, err := executeDebugPodCommand(nodeName, cmd)

					if err != nil {
						// If config.json doesn't exist, try the YAML format
						cmd = []string{"cat", "/host/var/lib/kubelet/config.yaml"}
						output, err = executeDebugPodCommand(nodeName, cmd)
					}

					if err != nil {
						GinkgoWriter.Printf("Warning: Could not read kubelet config from node %s: %v\n", nodeName, err)
						GinkgoWriter.Printf("Skipping enforcement check - config file may be in different location\n")
						Skip(fmt.Sprintf("Kubelet config not accessible on node %s", nodeName))
					}

					By("Verifying enforceNodeAllocatable includes system-reserved")
					// enforceNodeAllocatable should include "pods" and may include "system-reserved"
					// Common values: ["pods"], ["pods","system-reserved"], ["pods","system-reserved","kube-reserved"]

					if strings.Contains(output, "enforceNodeAllocatable") {
						// Check if system-reserved is in the list
						if strings.Contains(output, "system-reserved") {
							GinkgoWriter.Printf("✓ Node %s has system-reserved enforcement enabled\n", nodeName)
						} else {
							GinkgoWriter.Printf("⚠ Node %s: enforceNodeAllocatable does not include system-reserved (may use default enforcement)\n", nodeName)
						}
					}

					By("Verifying systemReservedCgroup is configured")
					// systemReservedCgroup is typically "/system.slice"
					if strings.Contains(output, "systemReservedCgroup") {
						if strings.Contains(output, "/system.slice") {
							GinkgoWriter.Printf("✓ Node %s has systemReservedCgroup set to /system.slice\n", nodeName)
						} else {
							GinkgoWriter.Printf("⚠ Node %s: systemReservedCgroup found but not /system.slice\n", nodeName)
						}
					} else {
						GinkgoWriter.Printf("Note: Node %s kubelet config does not specify systemReservedCgroup (may use default)\n", nodeName)
					}

					// At minimum, verify the node has allocatable resources properly set
					// which indicates systemReserved is in effect
					allocatable := nodeObj.Status.Allocatable
					capacity := nodeObj.Status.Capacity

					cpuAllocatable := allocatable[corev1.ResourceCPU]
					cpuCapacity := capacity[corev1.ResourceCPU]

					Expect(cpuAllocatable.Cmp(cpuCapacity)).To(Equal(-1),
						fmt.Sprintf("Node %s allocatable CPU (%s) should be less than capacity (%s), indicating systemReserved is in effect",
							nodeName, cpuAllocatable.String(), cpuCapacity.String()))

					GinkgoWriter.Printf("✓ Node %s has systemReserved enforcement in effect (allocatable < capacity)\n", nodeName)
				})
			}
		}

		When("Validating control plane node enforcement", func() {
			testNodeEnforcement(controlPlaneNodes, "control-plane")
		})

		When("Validating worker node enforcement", func() {
			testNodeEnforcement(workerNodes, "worker")
		})
	})

	Context("Scale lab baseline validation", func() {
		It("Should have systemReserved values adequate for scale lab requirements", func() {
			By("Checking control plane CPU systemReserved against scale lab baseline")
			cpuCores, err := tsparams.GetControlPlaneCPUCores()
			Expect(err).ToNot(HaveOccurred(), "Failed to parse control plane CPU reserved")

			scaleLabMax := tsparams.ScaleLabControlPlaneCPUMax
			Expect(cpuCores).To(BeNumerically(">=", scaleLabMax),
				fmt.Sprintf("Control plane CPU systemReserved (%.1f cores) should be >= scale lab max (%.1f cores)",
					cpuCores, scaleLabMax))
			GinkgoWriter.Printf("✓ Control plane CPU systemReserved (%.1f cores) meets scale lab requirement (%.1f cores)\n",
				cpuCores, scaleLabMax)

			By("Checking control plane memory systemReserved against scale lab baseline")
			memoryQuantity, err := resource.ParseQuantity(tsparams.ControlPlaneMemoryReserved)
			Expect(err).ToNot(HaveOccurred(), "Failed to parse control plane memory reserved")

			memoryGB := float64(memoryQuantity.Value()) / (1024 * 1024 * 1024)
			scaleLabMaxMemory := tsparams.ScaleLabControlPlaneMemoryMax

			if memoryGB < scaleLabMaxMemory {
				GinkgoWriter.Printf("⚠ WARNING: Control plane memory systemReserved (%.1f GB) is BELOW scale lab max (%.1f GB)\n",
					memoryGB, scaleLabMaxMemory)
				GinkgoWriter.Printf("⚠ Consider increasing to at least 34Gi for production environments\n")
			} else {
				GinkgoWriter.Printf("✓ Control plane memory systemReserved (%.1f GB) meets scale lab requirement (%.1f GB)\n",
					memoryGB, scaleLabMaxMemory)
			}

			By("Verifying worker systemReserved meets baseline requirements")
			workerCPUMillicores, err := tsparams.GetWorkerCPUMillicores()
			Expect(err).ToNot(HaveOccurred(), "Failed to parse worker CPU reserved")
			Expect(workerCPUMillicores).To(BeNumerically(">=", 500),
				fmt.Sprintf("Worker CPU systemReserved (%dm) should be >= minimum requirement (500m)", workerCPUMillicores))

			GinkgoWriter.Printf("✓ Worker CPU systemReserved (%dm) meets minimum requirement (500m)\n", workerCPUMillicores)
		})
	})
})

// Helper functions

// executeDebugPodCommand executes a command on a node via debug pod.
func executeDebugPodCommand(nodeName string, cmd []string) (string, error) {
	debugPodName := fmt.Sprintf("systemreserved-debug-%s", strings.ReplaceAll(nodeName, ".", "-"))
	debugNamespace := "default"

	// Create debug pod that mounts host filesystem
	debugPod := pod.NewBuilder(
		APIClient,
		debugPodName,
		debugNamespace,
		"registry.access.redhat.com/ubi8/ubi-minimal:latest",
	)

	// Configure pod to run on specific node with host filesystem access
	debugPod.WithNodeSelector(map[string]string{
		"kubernetes.io/hostname": nodeName,
	})

	// Mount /etc from host as /host/etc
	debugPod.Definition.Spec.Volumes = []corev1.Volume{
		{
			Name: "host-etc",
			VolumeSource: corev1.VolumeSource{
				HostPath: &corev1.HostPathVolumeSource{
					Path: "/etc",
				},
			},
		},
	}

	debugPod.Definition.Spec.Containers[0].VolumeMounts = []corev1.VolumeMount{
		{
			Name:      "host-etc",
			MountPath: "/host/etc",
			ReadOnly:  true,
		},
	}

	// Keep pod running for command execution
	debugPod.Definition.Spec.Containers[0].Command = []string{"/bin/sh", "-c", "sleep 300"}

	// Set privileged security context
	debugPod.Definition.Spec.Containers[0].SecurityContext = &corev1.SecurityContext{
		Privileged: func(b bool) *bool { return &b }(true),
	}

	// Create and wait for pod to be running
	GinkgoWriter.Printf("Creating debug pod %s on node %s\n", debugPodName, nodeName)
	_, err := debugPod.CreateAndWaitUntilRunning(2 * time.Minute)
	if err != nil {
		return "", fmt.Errorf("failed to create debug pod on node %s: %v", nodeName, err)
	}

	// Execute the command
	GinkgoWriter.Printf("Executing command in debug pod: %v\n", cmd)
	output, err := debugPod.ExecCommand(cmd, debugPod.Definition.Spec.Containers[0].Name)
	if err != nil {
		// Try to cleanup even if command failed
		cleanupErr := debugPod.DeleteAndWait(30 * time.Second)
		if cleanupErr != nil {
			GinkgoWriter.Printf("Warning: failed to delete debug pod: %v\n", cleanupErr)
		}
		return "", fmt.Errorf("failed to execute command on node %s: %v", nodeName, err)
	}

	// Cleanup debug pod
	GinkgoWriter.Printf("Cleaning up debug pod %s\n", debugPodName)
	err = debugPod.DeleteAndWait(30 * time.Second)
	if err != nil {
		GinkgoWriter.Printf("Warning: failed to delete debug pod: %v\n", err)
		// Don't return error for cleanup failure - we got the output
	}

	return string(output), nil
}

// parseEnvFile parses environment variable file content into a map.
func parseEnvFile(content string) map[string]string {
	envVars := make(map[string]string)
	lines := strings.Split(content, "\n")

	for _, line := range lines {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}

		parts := strings.SplitN(line, "=", 2)
		if len(parts) == 2 {
			key := strings.TrimSpace(parts[0])
			value := strings.TrimSpace(parts[1])
			envVars[key] = value
		}
	}

	return envVars
}

// normalizeCPUValue normalizes CPU value to millicores for comparison.
// Handles: "40" (cores), "40000m" (millicores), "1000m", "1".
func normalizeCPUValue(cpuStr string) int64 {
	cpuStr = strings.TrimSpace(cpuStr)

	// If ends with 'm', parse as millicores
	if strings.HasSuffix(cpuStr, "m") {
		millis, err := strconv.ParseInt(cpuStr[:len(cpuStr)-1], 10, 64)
		if err != nil {
			return 0
		}
		return millis
	}

	// Otherwise parse as cores and convert to millicores
	cores, err := strconv.ParseFloat(cpuStr, 64)
	if err != nil {
		return 0
	}
	return int64(cores * 1000)
}
